### ISSUE TITLE
Outdated examples

### ISSUE THREAD

**Issue by Nehmulos** [samvv/ramunk#1]
Hello, it would be nice if the examples would work. They haven't been updated in a while and are probably not in sync the with the current code any more.
In case I'm just running them incorrectly, it would be nice if the README would mention how to run them (I assume `cd examples; racket <example.rkt>`).

**Comment by samvv** [comment]
Even though this issue is really old, I think it is worth mentioning that the examples have been removed. In the next couple of days I will be adding some new ones with the new (stable) API.

Thanks for the feedback from a long time ago,
Sam

**Comment by samvv** [comment]
I've very quickly made an example that should work. It doesn't show much, but at least it should prove that the bindings work. Closing this for now.
